### PR TITLE
docs: Update main Sapphire page content

### PR DESCRIPTION
**Pull request by aefhm**
## Description

Use new Sapphire page content and update anchors to reference Network page.

Fix links introduced in #402.

```sh
  Exhaustive list of all broken anchors found:
  - Broken anchor on source page path = /dapp/sapphire/browser:
     -> linking to /dapp/sapphire/#testnet
  - Broken anchor on source page path = /dapp/sapphire/guide:
     -> linking to /dapp/sapphire/#rpc-endpoints
```
https://github.com/oasisprotocol/docs/actions/runs/10951224600/job/30407909516?pr=940

### CODE REVIEW

**Review by CedarMist — CHANGES_REQUESTED** [review]
Netlify build is still failing
```
1:59:06 AM: [ERROR] Client bundle compiled with errors therefore further build is impossible.
1:59:06 AM: Error: MDX compilation failed for file "/opt/build/repo/docs/.oasis-docs/docs/dapp/sapphire/browser.md"
1:59:06 AM: Cause: Docs markdown link couldn't be resolved: (./network.mdx) in source file "/opt/build/repo/docs/.oasis-docs/docs/dapp/sapphire/browser.md" for version current
Details:
1:59:06 AM: Error: Docs markdown link couldn't be resolved: (./network.mdx) in source file "/opt/build/repo/docs/.oasis-docs/docs/dapp/sapphire/browser.md" for version current
```

**Comment by rube-de** [comment]
is there a way to rerun the deploy preview? 
I think this is fixed with the bump of the submodule in doc.

**Review by rube-de — APPROVED** [review]

**Comment by aefhm** [comment]
> is there a way to rerun the deploy preview? I think this is fixed with the bump of the submodule in doc.

Yeah. We can rerun the job, and that should trigger it. In this case, I don't think the bump would work because the `docs` referred to this build is the `main` branch head which does not have symlinks introduced in https://github.com/oasisprotocol/docs/pull/940 to find the correct `./network.mdx` file.

```sh
9:38:18 AM: [ERROR] Client bundle compiled with errors therefore further build is impossible.
9:38:18 AM: Error: MDX compilation failed for file "/opt/build/repo/docs/.oasis-docs/docs/dapp/sapphire/browser.md"
9:38:18 AM: Cause: Docs markdown link couldn't be resolved: (./network.mdx) in source file "/opt/build/repo/docs/.oasis-docs/docs/dapp/sapphire/browser.md" for version current
Details:
9:38:18 AM: Error: Docs markdown link couldn't be resolved: (./network.mdx) in source file "/opt/build/repo/docs/.oasis-docs/docs/dapp/sapphire/browser.md" for version current
error Command failed with exit code 1. (https://ntl.fyi/exit-code-1)
```

I believe this is just a quirk of the current setup which is fine because deployment of the docs happen from https://github.com/oasisprotocol/docs repository, so we can freely bump `sapphire-paratime` without breaking end user experience. We just have to ensure that the preview works correctly in `docs` before merging.

_Note_ that most workflow functionality with Netlify preview should work as expected with the exception of these scenarios where a new file is introduced and referenced immediately. One workaround is to introduce a non-breaking change PR A in this repository. Update `docs` with PR B, and then opt for removal with PR C here.

**Comment by aefhm** [comment]
I'll give a stab to the symlink directory solution @CedarMist suggested separately. https://github.com/oasisprotocol/docs/pull/951

**Comment by aefhm** [comment]
Once https://github.com/oasisprotocol/docs/pull/951 and https://github.com/oasisprotocol/docs/pull/940 are merge, this deploy preview should work because all dependencies would be in the `sapphire-paratime` repo.

**Comment by aefhm** [comment]
Once https://github.com/oasisprotocol/docs/pull/951 and https://github.com/oasisprotocol/docs/pull/940 are merge, this deploy preview should work because all dependencies would be in the `sapphire-paratime` repo.

**Review by CedarMist — APPROVED** [review]
